### ISSUE TITLE
 项目中同时使用私有组件库和antd 组件库提示问题

### ISSUE THREAD

**Issue by chenwll** [common-intellisense/common-intellisense#13]
# 单独使用私包，提示没有问题
<img width="1079" alt="image" src="https://github.com/user-attachments/assets/b694e38e-656c-4e9e-87b3-0f74c91e55b7">

```
import './App.css'
import {HCheckbox} from '@baidu/health-ui'

function App() {
  return (
    <>
        <HCheckbox></HCheckbox>
    </>
  )
}

export default App
```
# 私有组件库和antd一起使用时
## 私有组件库提示有问题：鼠标hover到私有组件名上没有提示，hover到属性上提示正常
<img width="1059" alt="image" src="https://github.com/user-attachments/assets/bc56e0eb-fa33-47af-a5f2-b15c64ebef87">

```
import './App.css'
import {HPopup} from '@baidu/health-ui'
import {Button} from 'antd';
function App() {
  return (
    <>
        <Button></Button>
        <HPopup show duration={300} offsetHeight=""></HPopup>
    </>
  )
}

export default App
```

**Comment by Simon-He95** [comment]
86a73ee98c1d07e67b4716c0b94a93c26b6f315b
