### ISSUE TITLE
" 从远程拉取UI包失败，请检查代理 "

### ISSUE THREAD

**Issue by mvpyangxu** [common-intellisense/common-intellisense#16]
<img width="466" alt="image" src="https://github.com/user-attachments/assets/3a71ed43-ab5c-4ffb-b070-d57d8b82261c">

大佬，想问一下这个怎么解决，vscode没有设置过代理

**Comment by Simon-He95** [comment]
<img width="969" alt="image" src="https://github.com/user-attachments/assets/05dda199-2edc-43fd-9ff9-22660e88715f">

需要你提供一下这个终端这里的日志

**Comment by mvpyangxu** [comment]
[INFO] common-intellisense activate!
[INFO] 正在读取 /Users/yangxu/.vscode/extensions/simonhe.common-intellisense-0.2.39/dist/mapping.json 中的数据
[INFO] 缓存读取完毕, 已缓存的 key: @common-intellisense/element-ui2@0.0.3 | @common-intellisense/element-plus2@0.0.1 | @common-intellisense/element-ui2@0.0.4 | @common-intellisense/vuetify3@0.0.4 | @common-intellisense/antd5@0.0.1 | /Users/Simon/Github/lazy-js-utils/index.cjs
[INFO] 正在查找 @common-intellisense/element-ui2 的最新版本...
[INFO] 找到 @common-intellisense/element-ui2 的最新版本: 0.0.4
[INFO] 已缓存的 @common-intellisense/element-ui2@0.0.4
[ERROR] Error: Command failed: npm pack @common-intellisense/element-ui2 --pack-destination /Users/yangxu/.vscode/extensions/simonhe.common-intellisense-0.2.39/dist/temp
npm ERR! code ENOLOCAL
npm ERR! Could not install from "Users/yangxu/.vscode/extensions/simonhe.common-intellisense-0.2.39/dist/temp" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yangxu/.npm/_logs/2024-10-28T06_46_59_434Z-debug.log

[INFO] findUI: element-ui@2.15.14
[INFO] 正在查找 @common-intellisense/element-ui2 的最新版本...
[INFO] 找到 @common-intellisense/element-ui2 的最新版本: 0.0.4
[INFO] 已缓存的 @common-intellisense/element-ui2@0.0.4
[ERROR] Error: Command failed: npm pack @common-intellisense/element-ui2 --pack-destination /Users/yangxu/.vscode/extensions/simonhe.common-intellisense-0.2.39/dist/temp
npm ERR! code ENOLOCAL
npm ERR! Could not install from "Users/yangxu/.vscode/extensions/simonhe.common-intellisense-0.2.39/dist/temp" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yangxu/.npm/_logs/2024-10-28T06_47_22_464Z-debug.log

[INFO] findUI: element-ui@2.15.14

<img width="1501" alt="image" src="https://github.com/user-attachments/assets/efa539e0-cfb5-4e1c-b9d0-7199f1c28b02">

**Comment by Simon-He95** [comment]
你试试看是不是这个extension下的目录没有权限导致的

**Comment by mvpyangxu** [comment]
我看了看，读写权限都是有的

**Comment by Simon-He95** [comment]
<img width="652" alt="image" src="https://github.com/user-attachments/assets/7d461ec7-d715-4281-9bf7-dca2a56c45e6">

你直接执行这个命令试试可以成功吗

**Comment by Simon-He95** [comment]
把插件卸载一下，装最新的看一下日志，之前版本有拉取成功之后就会缓存所以不能作为参考

**Comment by Simon-He95** [comment]
另外可能和你本地的npm版本过低有关系，可以尝试升级一下

**Comment by Simon-He95** [comment]
最新版本兼容node 低版本的 问题了，尝试下 v0.2.42

**Comment by mvpyangxu** [comment]
大佬，刚刚看了一下，最新的v0.2.42还是不行，还是报错"从远程拉取UI包失败，请检查代理" 。还是只能到v0.2.36。

**Comment by Simon-He95** [comment]
<img width="769" alt="image" src="https://github.com/user-attachments/assets/29b6d718-3f05-4fca-8c45-613b67dde19d">

还是这个报错吗，这个问题是因为本地 node 版本应该是 14 和 14 以下执行 npm pack 的报错，新版本应该修复了，你尝试卸载重新安装一下呢，或者尝试切换 node 版本到更高的版本试试

**Comment by mvpyangxu** [comment]
好的好的，谢谢大佬百忙之中还能有如此高的效率回复，卸载重装试过了，node版本的话我晚点试试，再次感谢

**Comment by 98Protein** [comment]
> 最新版本兼容node 低版本的 问题了，尝试下 v0.2.42

我也是v0.2.42版本，没升级插件版本之前都好好的，升级之后，频发”从远程拉取UI包失败，请检查代理“的问题，本地node版本v18.18.2

**Comment by Simon-He95** [comment]
> > 最新版本兼容node 低版本的 问题了，尝试下 v0.2.42
> 
> 我也是v0.2.42版本，没升级插件版本之前都好好的，升级之后，频发”从远程拉取UI包失败，请检查代理“的问题，本地node版本v18.18.2

能提供终端的common-Intellisense的错误信息吗

**Comment by 2815261401** [comment]
我也是v0.2.42版本,第一次打开项目也有这个报错,但是插件可以使用
![image](https://github.com/user-attachments/assets/2db6b4a9-6898-4ab8-a4f3-3d57623f1140)

**Comment by Simon-He95** [comment]
> 我也是v0.2.42版本,第一次打开项目也有这个报错,但是插件可以使用 ![image](https://private-user-images.githubusercontent.com/71112636/381797390-2db6b4a9-6898-4ab8-a4f3-3d57623f1140.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDA1OTQsIm5iZiI6MTczMDM0MDI5NCwicGF0aCI6Ii83MTExMjYzNi8zODE3OTczOTAtMmRiNmI0YTktNjg5OC00YWI4LWE0ZjMtM2Q1NzYyM2YxMTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDAyMDQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNzA0NzY3M2M1YTA4OWVhZmRjMWM5NjQ1NjBiMmVkNDk5ODA2OGJjNjYyMGExNDUxMGVlMzA2Nzk0MDAyMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kW6b_40TMRE9-Xtp3z_qD-Fh8KsXGYKwhEKykoj2ZOE)

<img width="324" alt="image" src="https://github.com/user-attachments/assets/5c964e56-8e15-4524-a9f0-1cb3bc1f958c">
提示了这个目录没有权限

**Comment by 2815261401** [comment]
[ERROR] Error: TAR_BAD_ARCHIVE: Unrecognized archive format
应该是这个导致的

**Comment by Simon-He95** [comment]
这个是因为 extension 目录的权限问题，他要操作 npm download 下来的 .tgz 文件没有权限，但是确实有一个问题是，因为你本地已经成功 download 过一次了，代码里面没有读缓存，而是有去远程拉代码了，我把这里优化了

**Comment by mvpyangxu** [comment]
升级到今天的v0.2.43之后，报错和上面一样
“[ERROR] Error: TAR_BAD_ARCHIVE: Unrecognized archive format”

回退到v0.2.36，可以正常使用。

**Comment by wanglei1020** [comment]
今天第一次安装，v0.2.43版本。同样的问题，看作者回复是扩展目录的权限问题。尝试vscode右键以管理员权限打开，成功下载。后面使用普通权限也能正常使用。

**Comment by mvpyangxu** [comment]
mac上权限都是有的，算了不折腾了，先使用v0.2.36版本吧😅

**Comment by Simon-He95** [comment]
可以尝试一下最新的版本，做了一些失败的兼容处理

**Comment by mvpyangxu** [comment]
v0.2.44版本，element项目还是不行，ant-design不报错了 👍🏻
<img width="422" alt="image" src="https://github.com/user-attachments/assets/5a012fbd-e100-4b26-b433-bd67a64b0291">
![image](https://github.com/user-attachments/assets/575e6ec2-f4e7-499d-9d59-9f28d6e6d475)

**Comment by Simon-He95** [comment]
我本地复现不了，这个错误看上去是tar.x解压.tgz文件失败了，可能是某个源download下来的.tgz被压缩过了tar.x智能处理原始的，但是我本地切换了几个源都测试过了可以成功解压，所以我加入了之前老的方式直接从请求获取cjs的逻辑，应该能兼容这个场景，尝试更新到 0.2.46 看看是否能解决

**Comment by xiaoyaobishizhe** [comment]
配置系统代理没用，我关了系统代理，开Tun模式，直接下载成功。关掉Tun模式，开启系统代理，之后再次打开Vscode，也可以正常打开。

**Comment by xiaoyaobishizhe** [comment]
问题是每次打开vscode都会自动开很多次终端，看着实属难受，不知道能不能去掉。

**Comment by Simon-He95** [comment]
> 问题是每次打开vscode都会自动开很多次终端，看着实属难受，不知道能不能去掉。

你说的是消息弹窗？

**Comment by Simon-He95** [comment]
> 配置系统代理没用，我关了系统代理，开Tun模式，直接下载成功。关掉Tun模式，开启系统代理，之后再次打开Vscode，也可以正常打开。

如果这个组件库拉取成功过一次之后如果没更新，会有缓存:p

**Comment by zhangta** [comment]
v0.2.59

![Snipaste_2024-11-21_10-33-30](https://github.com/user-attachments/assets/3b77c51b-7890-416c-8172-0bdb5c89c56e)
