### ISSUE TITLE
插件升级后会自动打开Windows Terminal

### ISSUE THREAD

**Issue by HuangYundong** [common-intellisense/common-intellisense#19]
Vscode 插件升级到v0.2.55后，会自动打开Windows Terminal，Tab 名称显示 npm show @common-Intellisense，并且进入死循环，关掉后又打开了，版本回退到v.0.2.49就正常了~

![17318967888663](https://github.com/user-attachments/assets/212cba8b-358e-49cd-a0f2-617fb40896e6)

**Comment by Simon-He95** [comment]
试一下 v0.2.56

**Comment by imlinhanchao** [comment]
还是一样，我是弹窗 cmd

**Comment by Simon-He95** [comment]
v0.2.57 应该可以了 stdio 默认用的 inherit 在 win 会打开新的终端
